// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: message_server.proto

package go_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageServer_GetMessage_FullMethodName = "/message_server.MessageServer/GetMessage"
)

// MessageServerClient is the client API for MessageServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServerClient interface {
	GetMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*Message, error)
}

type messageServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServerClient(cc grpc.ClientConnInterface) MessageServerClient {
	return &messageServerClient{cc}
}

func (c *messageServerClient) GetMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MessageServer_GetMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServerServer is the server API for MessageServer service.
// All implementations must embed UnimplementedMessageServerServer
// for forward compatibility.
type MessageServerServer interface {
	GetMessage(context.Context, *MessageRequest) (*Message, error)
	mustEmbedUnimplementedMessageServerServer()
}

// UnimplementedMessageServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageServerServer struct{}

func (UnimplementedMessageServerServer) GetMessage(context.Context, *MessageRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessage not implemented")
}
func (UnimplementedMessageServerServer) mustEmbedUnimplementedMessageServerServer() {}
func (UnimplementedMessageServerServer) testEmbeddedByValue()                       {}

// UnsafeMessageServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServerServer will
// result in compilation errors.
type UnsafeMessageServerServer interface {
	mustEmbedUnimplementedMessageServerServer()
}

func RegisterMessageServerServer(s grpc.ServiceRegistrar, srv MessageServerServer) {
	// If the following call pancis, it indicates UnimplementedMessageServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageServer_ServiceDesc, srv)
}

func _MessageServer_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServerServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageServer_GetMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServerServer).GetMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageServer_ServiceDesc is the grpc.ServiceDesc for MessageServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message_server.MessageServer",
	HandlerType: (*MessageServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessage",
			Handler:    _MessageServer_GetMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message_server.proto",
}
